/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FileEntry {
  'id' : bigint,
  'content' : string,
  'name' : string,
}
export interface Note { 'id' : bigint, 'content' : string }
export interface _SERVICE {
  'addFile' : ActorMethod<[string, string], undefined>,
  'addNote' : ActorMethod<[string], undefined>,
  'deleteFileById' : ActorMethod<[bigint], undefined>,
  'deleteNoteById' : ActorMethod<[bigint], undefined>,
  'getAllFiles' : ActorMethod<[], Array<FileEntry>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'hasPin' : ActorMethod<[], boolean>,
  'setPin' : ActorMethod<[string], undefined>,
  'verifyPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];