/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FileEntry = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'name' : IDL.Text,
});
export const Note = IDL.Record({ 'id' : IDL.Nat, 'content' : IDL.Text });

export const idlService = IDL.Service({
  'addFile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addNote' : IDL.Func([IDL.Text], [], []),
  'deleteFileById' : IDL.Func([IDL.Nat], [], []),
  'deleteNoteById' : IDL.Func([IDL.Nat], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileEntry)], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], []),
  'hasPin' : IDL.Func([], [IDL.Bool], []),
  'setPin' : IDL.Func([IDL.Text], [], []),
  'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FileEntry = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'name' : IDL.Text,
  });
  const Note = IDL.Record({ 'id' : IDL.Nat, 'content' : IDL.Text });
  
  return IDL.Service({
    'addFile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addNote' : IDL.Func([IDL.Text], [], []),
    'deleteFileById' : IDL.Func([IDL.Nat], [], []),
    'deleteNoteById' : IDL.Func([IDL.Nat], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileEntry)], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], []),
    'hasPin' : IDL.Func([], [IDL.Bool], []),
    'setPin' : IDL.Func([IDL.Text], [], []),
    'verifyPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };